import  { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>{children}</body>
        <footer className="bg-gray-200 p-4 text-center fixed bottom-0 w-screen">
      <p className="text-sm text-gray-600">
        Created with{' '}
        <span role="img" aria-label="Heart">
          ❤️
        </span>{' '}
        by <a href='https://github.com/Bashamega' className=' underline'>Adam Basha</a>
      </p>
    </footer>
    </html>
  )
}
